/**
 * Script Name: cleanup-jenkins-config-history.groovy
 * Target: Jenkins Script Console (Manage Jenkins -> Script Console)
 * Description: Recursively scans /var/jenkins_home/config-history/ across all 
 *              directory depths and purges timestamped config backups older than X days.
 * Safe for: JaaS / Cloud environments without direct SSH/filesystem access.
 */

import jenkins.model.Jenkins
import java.nio.file.Files
import java.nio.file.Path
import java.util.Calendar

// Threshold: Delete history entries older than this many days
int maxAgeInDays = 14

File historyRootDir = new File(Jenkins.instance.rootDir, "config-history")

if (!historyRootDir.exists()) {
    println "Directory does not exist: ${historyRootDir.absolutePath}"
    return
}

Calendar cal = Calendar.getInstance()
cal.add(Calendar.DAY_OF_YEAR, -maxAgeInDays)
long cutoffTime = cal.getTimeInMillis()

// Regex for timestamp folders generated by the plugin (e.g., 2021-11-06_07-29-18)
def timestampPattern = ~/^\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}$/

List<File> targetDirs = []

println "Scanning for config history folders at all directory depths..."

// Step 1: Walk the entire tree safely to find all timestamped history folders
Files.walk(historyRootDir.toPath()).forEach { Path path ->
    File file = path.toFile()
    if (file.isDirectory() && (file.name =~ timestampPattern)) {
        if (file.lastModified() < cutoffTime) {
            targetDirs.add(file)
        }
    }
}

println "Found ${targetDirs.size()} history entries older than ${maxAgeInDays} days."

long totalBytesDeleted = 0
int deletedCount = 0

// Step 2: Delete collected directories safely
targetDirs.each { dir ->
    long dirSize = 0
    dir.eachFileRecurse { f -> dirSize += f.length() }
    
    if (dir.deleteDir()) {
        totalBytesDeleted += dirSize
        deletedCount++
    }
    
    if (deletedCount % 1000 == 0 && deletedCount > 0) {
        println "Progress: Cleaned ${deletedCount} entries..."
    }
}

println "--- Cleanup Complete ---"
println "Deleted ${deletedCount} history entries."
println "Space reclaimed: ${String.format('%.2f', totalBytesDeleted / (1024 * 1024 * 1024))} GB"
